severity: low
exclude:
  - message: Giphy links
    pattern: https://media.giphy.com/media

  - message: Dependencies
    paths:
      - node_modules
      - venv

  - message: Tooling outputs
    paths:
      - .DS_Store
      - docs/dist
      - requirements.txt
      - yarn-error.log
      - yarn.lock
